language: d
d:
  - dmd-nightly
  - dmd-beta
  - dmd
  - ldc-beta
  - ldc
sudo: false
script:
  - cd test && ./run_tests.sh && cd ..
  - find test/coverage -type f -exec mv {} . \;
after_success:
 - bash <(curl -s https://codecov.io/bash)
