sudo: false
language: d
d:
  - dmd
  - dmd-2.075.0
  - ldc
matrix:
  include:
    d: dmd-2.078.2
    env: [DEPLOY=1]
    # ddox dependencies (can be removed after 0.8.3 has been released)
    addons:
      apt:
        packages:
          - libevent-dev
script:
  # note: for dlang project tester, which doesn't clone automatically
  - git submodule update --init --recursive
  #
  - cd test && ./run_tests.sh && cd ..
  - find test/coverage -type f -exec mv {} . \;
after_success:
 - bash <(curl -s https://codecov.io/bash)
